# Generated by Django 4.0.5 on 2022-09-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkLister', '0002_field_listinginfo_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='index',
            field=models.IntegerField(),
        ),
    ]
